### PR TITLE
Migration/gatsby#2

### LINKED ISSUE #3: Lighthouse audit reports issues
I checked the demo linked in the readme with the Lighthouse audit in Chrome and it reports room for improvement. Some of those issues should be easy to fix. If I find the time this week, I will try to fix some of those.

screen shot 2018-07-23 at 20 01 38
screen shot 2018-07-23 at 20 01 57

### PR DESCRIPTION
**Pull request by ttristan**
- [x] Performance 85 -> 91
- [x] PWA 73 -> 100
- [x] Accessibility 55 -> 100
- [x] Best Practices 81 -> 100
- [x] SEO 85 -> 100

fixes #3

### CODE REVIEW

**Comment by virtualandy** [comment]
Anything we can help test or try to get this merged? I realize Gatsby V2 is still unofficial, heh.
Want to start using this template (and am happy to use @ttristan's fork - thanks @ttristan ) so just curious on status. Thanks for putting it together in the first place!

**Comment by RyanFitzgerald** [comment]
Thanks for your interest in it! This was put on hold temporarily waiting on an official release of V2 which should be coming soon. Most of the testing is done and all the work @ttristan put in looks great. If you're using the fork and notice anything, definitely feel free to open an issue or let us know. In the mean time, I may merge it into a separate branch and then merge that into the main branch once it's officially released. Hope that helps.

**Comment by virtualandy** [comment]
Makes sense and no worries. Will keep my eye on the fork to see if anything is amiss. [So far so good...](https://www.nomatter.press)

**Comment by RyanFitzgerald** [comment]
Revisiting this now that V2 is officially released.

**Comment by RyanFitzgerald** [comment]
Sorry for the delay on this, all the changes look good and work with the upgrade. There are a couple issues I'll address since a couple things have changed since this PR, but that's on me. Thanks again for the work yo u put into this.

**Comment by ttristan** [comment]
Good stuff, nice to see it finally merged :)

**Pull request merged**
